#!/bin/bash

###################################
## PRE COMMIT HOOK
###################################

## Prevent debug functions
##dkgithookspath##prevent-debug-functions.sh

## Prevent core edit
##dkgithookspath##prevent-core-edit.sh

